### ISSUE TITLE
CNM-17: Đổi quà

### ISSUE THREAD

**Issue by vyhungle** [Cinema-77/cinema-server-express#12]

**Comment by vyhungle** [comment]
## Get list gift
`Api`  https://server-api-cinema.herokuapp.com/api/coupon/gift/get-all?screenId=61644b08df1b9d2700e43b23
`Note` nếu truyền screenId vô thì nó sẽ query quà tằng loại vé theo loại màng hình (2D,3D,IMAX)

@longngo0617

**Comment by vyhungle** [comment]
## Create coupon
`Api` https://server-api-cinema.herokuapp.com/api/coupon/coupon/create-coupon
`Authorization`: Bearer token
`Method` Post
`Body` 
{

        "giftId": "618293aab3b05642dc7bf89f", // mã quà tặng
        "userId": mã // chỉ dùng dưới cms, trên client k cần field này  

} 
`Res` 
![image](https://user-images.githubusercontent.com/72851530/140101638-dd447f75-79a3-49ff-96d8-431e057bfaee.png)
@longngo0617 @t1112000

**Comment by longngo0617** [comment]
> ## Create coupon
> `Api` https://server-api-cinema.herokuapp.com/api/coupon/coupon/create-coupon `Authorization`: Bearer token `Method` Post `Body` {
> 
> ```
>     "giftId": "618293aab3b05642dc7bf89f", // mã quà tặng
>     "userId": mã // chỉ dùng dưới cms, trên client k cần field này  
> ```
> 
> } `Res` ![image](https://user-images.githubusercontent.com/72851530/140101638-dd447f75-79a3-49ff-96d8-431e057bfaee.png) @longngo0617 @t1112000

Create coupoun là sao ?
